baseurl: ""
url: "http://delo.soedinennost.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
metrika: 35781275

collections:
  webinars:
    output: true
    permalink: /webinar/:path/

defaults:
  - scope:
      path: ""
      type: webinars
    values:
      layout: listbuilder-webinar
