baseurl: ""
url: "http://delo.soedinennost.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
metrika: 35781275

collections:
  webinars:
    output: true
    permalink: /webinar/:path/
  tests:
    output: true
    permalink: /test/:path/

defaults:
  - scope:
      path: ""
      type: webinars
    values:
      layout: listbuilder-webinar-rec
  - scope:
      path: ""
      type: tests
    values:
      layout: listbuilder-test
